# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from convore_api_client.models.gmail_connector import GmailConnector
from convore_api_client.models.provider_type import ProviderType
from convore_api_client.models.ses_connector import SesConnector
from typing import Optional, Set
from typing_extensions import Self

class Connector(BaseModel):
    """
    Connector
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier of the connector.")
    provider: ProviderType
    name: StrictStr = Field(description="Name of the connector")
    gmail: Optional[GmailConnector] = None
    ses: Optional[SesConnector] = None
    created_at: datetime = Field(description="The ISO 8601 time at which the Connector was created.")
    __properties: ClassVar[List[str]] = ["id", "provider", "name", "gmail", "ses", "created_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Connector from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of gmail
        if self.gmail:
            _dict['gmail'] = self.gmail.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ses
        if self.ses:
            _dict['ses'] = self.ses.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Connector from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "provider": obj.get("provider"),
            "name": obj.get("name"),
            "gmail": GmailConnector.from_dict(obj["gmail"]) if obj.get("gmail") is not None else None,
            "ses": SesConnector.from_dict(obj["ses"]) if obj.get("ses") is not None else None,
            "created_at": obj.get("created_at")
        })
        return _obj


