# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from convore_api_client.models.event_type import EventType
from convore_api_client.models.object_type import ObjectType
from typing import Optional, Set
from typing_extensions import Self

class Event(BaseModel):
    """
    Event
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier of the event.")
    type: EventType
    object_id: StrictStr = Field(description="The ID of the object associated with the event.")
    object_type: ObjectType
    conversation_id: Optional[StrictStr] = Field(default=None, description="The ID of the conversation associated with the event.")
    message_id: Optional[StrictStr] = Field(default=None, description="The ID of the message associated with the event.")
    label_id: Optional[StrictStr] = Field(default=None, description="The ID of the label associated with the event.")
    created_at: datetime = Field(description="The ISO 8601 time at which the Event was created.")
    __properties: ClassVar[List[str]] = ["id", "type", "object_id", "object_type", "conversation_id", "message_id", "label_id", "created_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Event from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Event from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "object_id": obj.get("object_id"),
            "object_type": obj.get("object_type"),
            "conversation_id": obj.get("conversation_id"),
            "message_id": obj.get("message_id"),
            "label_id": obj.get("label_id"),
            "created_at": obj.get("created_at")
        })
        return _obj


