# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from convore_api_client.models.label_type import LabelType
from typing import Optional, Set
from typing_extensions import Self

class Label(BaseModel):
    """
    Label
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier of the label.")
    name: StrictStr = Field(description="The human-readable name of the label, used for easy identification. This name can be something descriptive related to the label's purpose, like 'Technical Support' or 'Urgent'.")
    description: Optional[StrictStr] = Field(default=None, description="An optional detailed description of the label, providing additional context about its purpose.")
    created_at: datetime = Field(description="The ISO 8601 time at which the Label was created.")
    type: LabelType
    channel_id: Optional[StrictStr] = Field(default=None, description="The identifier of the channel this label is associated with, required for CHANNEL_PRIVATE labels. This links the label to a specific communication channel.")
    external_label_id: Optional[StrictStr] = Field(default=None, description="Identifier of the label in an external system, required for CHANNEL_PRIVATE labels that map to external systems.")
    shared_label_id: Optional[StrictStr] = Field(default=None, description="An identifier used to associate this CHANNEL_PRIVATE label with a corresponding SHARED label within the organization, facilitating unified label management across different channels.")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "created_at", "type", "channel_id", "external_label_id", "shared_label_id"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Label from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Label from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "created_at": obj.get("created_at"),
            "type": obj.get("type"),
            "channel_id": obj.get("channel_id"),
            "external_label_id": obj.get("external_label_id"),
            "shared_label_id": obj.get("shared_label_id")
        })
        return _obj


