# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LabelType(str, Enum):
    """
    The type of the label, which determines its scope and usage. 'SHARED' labels are accessible across multiple channels, while 'CHANNEL_PRIVATE' labels are restricted to a specific channel. Note: When a 'SHARED' label is created and later applied to a conversation, the API automatically applies the corresponding 'CHANNEL_PRIVATE' label to the conversation in the specific channel, and vice versa.
    """

    """
    allowed enum values
    """
    SHARED = 'shared'
    CHANNEL_PRIVATE = 'channel_private'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LabelType from a JSON string"""
        return cls(json.loads(json_str))


