# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.create_label_request import CreateLabelRequest

class TestCreateLabelRequest(unittest.TestCase):
    """CreateLabelRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateLabelRequest:
        """Test CreateLabelRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateLabelRequest`
        """
        model = CreateLabelRequest()
        if include_optional:
            return CreateLabelRequest(
                name = 'Technical support',
                description = 'Urgent and important',
                type = 'SHARED',
                channel_id = 'chnnl_01h2xcejqtf2nbrexx3vqjhp41',
                external_label_id = 'ext_lbl_23kj2b3k4j2',
                shared_label_id = ''
            )
        else:
            return CreateLabelRequest(
                name = 'Technical support',
        )
        """

    def testCreateLabelRequest(self):
        """Test CreateLabelRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
