# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.create_draft_request import CreateDraftRequest

class TestCreateDraftRequest(unittest.TestCase):
    """CreateDraftRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateDraftRequest:
        """Test CreateDraftRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateDraftRequest`
        """
        model = CreateDraftRequest()
        if include_optional:
            return CreateDraftRequest(
                channel_id = 'chnnl_01h2xcejqtf2nbrexx3vqjhp41',
                conversation_id = 'chnnl_01h2xcejqtf2nbrexx3vqjhp41',
                reply_to_message_id = 'msg_01h2xcejqtf2nbrexx3vqjhp41',
                reply_type = 'reply',
                var_from = '',
                to = [
                    ''
                    ],
                cc = [
                    ''
                    ],
                bcc = [
                    ''
                    ],
                sender = convore_api_client.models.message_participant.MessageParticipant(
                    name = 'John Doe', 
                    handle = convore_api_client.models.contact_handle.ContactHandle(
                        type = 'email', 
                        value = 'john@example.com', ), 
                    role = 'from', ),
                recipients = [
                    convore_api_client.models.message_participant.MessageParticipant(
                        name = 'John Doe', 
                        handle = convore_api_client.models.contact_handle.ContactHandle(
                            type = 'email', 
                            value = 'john@example.com', ), 
                        role = 'from', )
                    ],
                subject = 'Re: Issue with Verification Process',
                body = '...',
                quote_body = 'On Dec 15, 2023, at 6:54 PM, John Doe <john@example.com> wrote: ...',
                raw_body = '...'
            )
        else:
            return CreateDraftRequest(
        )
        """

    def testCreateDraftRequest(self):
        """Test CreateDraftRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
