# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.channel_address import ChannelAddress

class TestChannelAddress(unittest.TestCase):
    """ChannelAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelAddress:
        """Test ChannelAddress
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelAddress`
        """
        model = ChannelAddress()
        if include_optional:
            return ChannelAddress(
                name = 'John Doe',
                handle = convore_api_client.models.contact_handle.ContactHandle(
                    type = 'email', 
                    value = 'john@example.com', ),
                is_primary = True
            )
        else:
            return ChannelAddress(
                handle = convore_api_client.models.contact_handle.ContactHandle(
                    type = 'email', 
                    value = 'john@example.com', ),
        )
        """

    def testChannelAddress(self):
        """Test ChannelAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
