# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.convore_mail_channel import ConvoreMailChannel

class TestConvoreMailChannel(unittest.TestCase):
    """ConvoreMailChannel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConvoreMailChannel:
        """Test ConvoreMailChannel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConvoreMailChannel`
        """
        model = ConvoreMailChannel()
        if include_optional:
            return ConvoreMailChannel(
                sender_name = 'John Smith',
                address = 'johnsmith@convoremail.com'
            )
        else:
            return ConvoreMailChannel(
                sender_name = 'John Smith',
                address = 'johnsmith@convoremail.com',
        )
        """

    def testConvoreMailChannel(self):
        """Test ConvoreMailChannel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
