# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.create_ses_channel_params import CreateSesChannelParams

class TestCreateSesChannelParams(unittest.TestCase):
    """CreateSesChannelParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSesChannelParams:
        """Test CreateSesChannelParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSesChannelParams`
        """
        model = CreateSesChannelParams()
        if include_optional:
            return CreateSesChannelParams(
                sns_topic_arn = ''
            )
        else:
            return CreateSesChannelParams(
        )
        """

    def testCreateSesChannelParams(self):
        """Test CreateSesChannelParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
