# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.api.channels_api import ChannelsApi


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChannelsApi()

    def tearDown(self) -> None:
        pass

    def test_create_channel(self) -> None:
        """Test case for create_channel

        Create a channel
        """
        pass

    def test_get_channel(self) -> None:
        """Test case for get_channel

        Retrieve a channel
        """
        pass

    def test_list_channels(self) -> None:
        """Test case for list_channels

        List channels
        """
        pass

    def test_update_channel(self) -> None:
        """Test case for update_channel

        Update a channel
        """
        pass


if __name__ == '__main__':
    unittest.main()
