# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.update_conversation_request import UpdateConversationRequest

class TestUpdateConversationRequest(unittest.TestCase):
    """UpdateConversationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateConversationRequest:
        """Test UpdateConversationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateConversationRequest`
        """
        model = UpdateConversationRequest()
        if include_optional:
            return UpdateConversationRequest(
                status = 'open',
                priority = 'no_priority',
                label_ids = [
                    ''
                    ],
                participants = [
                    convore_api_client.models.message_participant.MessageParticipant(
                        name = 'John Doe', 
                        handle = convore_api_client.models.contact_handle.ContactHandle(
                            type = 'email', 
                            value = 'john@example.com', ), 
                        role = 'from', )
                    ],
                subject = 'Issue with Verification Process',
                snippet = '',
                is_unread = True,
                last_message_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return UpdateConversationRequest(
        )
        """

    def testUpdateConversationRequest(self):
        """Test UpdateConversationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
