# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.provider_type import ProviderType

class TestProviderType(unittest.TestCase):
    """ProviderType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderType(self):
        """Test ProviderType"""
        # inst = ProviderType()

if __name__ == '__main__':
    unittest.main()
