# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.api.attachments_api import AttachmentsApi


class TestAttachmentsApi(unittest.TestCase):
    """AttachmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AttachmentsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_attachment(self) -> None:
        """Test case for delete_attachment

        Delete an attachment
        """
        pass

    def test_download_attachment(self) -> None:
        """Test case for download_attachment

        Download attachment content
        """
        pass

    def test_upload_attachment(self) -> None:
        """Test case for upload_attachment

        Upload an attachment
        """
        pass


if __name__ == '__main__':
    unittest.main()
