# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.message_reply_type import MessageReplyType

class TestMessageReplyType(unittest.TestCase):
    """MessageReplyType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageReplyType(self):
        """Test MessageReplyType"""
        # inst = MessageReplyType()

if __name__ == '__main__':
    unittest.main()
