# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.api.connectors_api import ConnectorsApi


class TestConnectorsApi(unittest.TestCase):
    """ConnectorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsApi()

    def tearDown(self) -> None:
        pass

    def test_create_connector(self) -> None:
        """Test case for create_connector

        Create a connector
        """
        pass

    def test_get_connector(self) -> None:
        """Test case for get_connector

        Retrieve a connector
        """
        pass

    def test_list_connectors(self) -> None:
        """Test case for list_connectors

        List connectors
        """
        pass

    def test_update_connector(self) -> None:
        """Test case for update_connector

        Update a connector
        """
        pass


if __name__ == '__main__':
    unittest.main()
