# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.api.inbound_webhooks_api import InboundWebhooksApi


class TestInboundWebhooksApi(unittest.TestCase):
    """InboundWebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InboundWebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_handle_inbound_webhook(self) -> None:
        """Test case for handle_inbound_webhook

        Send a webhook event to Convore
        """
        pass


if __name__ == '__main__':
    unittest.main()
