# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.import_message_request import ImportMessageRequest

class TestImportMessageRequest(unittest.TestCase):
    """ImportMessageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportMessageRequest:
        """Test ImportMessageRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportMessageRequest`
        """
        model = ImportMessageRequest()
        if include_optional:
            return ImportMessageRequest(
                conversation_id = 'conv_01h2xcejqtf2nbrexx3vqjhp41',
                channel_id = 'chnnl_01h2xcejqtf2nbrexx3vqjhp41',
                subject = 'Issue with Verification Process',
                direction = 'inbound',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sender = convore_api_client.models.message_participant.MessageParticipant(
                    name = 'John Doe', 
                    handle = convore_api_client.models.contact_handle.ContactHandle(
                        type = 'email', 
                        value = 'john@example.com', ), 
                    role = 'from', ),
                recipients = [
                    convore_api_client.models.message_participant.MessageParticipant(
                        name = 'John Doe', 
                        handle = convore_api_client.models.contact_handle.ContactHandle(
                            type = 'email', 
                            value = 'john@example.com', ), 
                        role = 'from', )
                    ],
                body = '',
                snippet = '',
                reply_to_message_id = 'msg_01h2xcejqtf2nbrexx3vqjhp41',
                reply_type = 'reply'
            )
        else:
            return ImportMessageRequest(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sender = convore_api_client.models.message_participant.MessageParticipant(
                    name = 'John Doe', 
                    handle = convore_api_client.models.contact_handle.ContactHandle(
                        type = 'email', 
                        value = 'john@example.com', ), 
                    role = 'from', ),
                recipients = [
                    convore_api_client.models.message_participant.MessageParticipant(
                        name = 'John Doe', 
                        handle = convore_api_client.models.contact_handle.ContactHandle(
                            type = 'email', 
                            value = 'john@example.com', ), 
                        role = 'from', )
                    ],
        )
        """

    def testImportMessageRequest(self):
        """Test ImportMessageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
