# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.attachment import Attachment

class TestAttachment(unittest.TestCase):
    """Attachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Attachment:
        """Test Attachment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Attachment`
        """
        model = Attachment()
        if include_optional:
            return Attachment(
                id = 'attch_01hcf9x766fqk8g7hz74363j9q',
                conversation_id = 'conv_01h2xcejqtf2nbrexx3vqjhp41',
                draft_id = 'drft_01h2xcejqtf2nbrexx3vqjhp41',
                message_id = '',
                content_type = 'image/png',
                filename = 'image.png',
                is_inline = True,
                content_id = '',
                size = 14039
            )
        else:
            return Attachment(
                id = 'attch_01hcf9x766fqk8g7hz74363j9q',
                conversation_id = 'conv_01h2xcejqtf2nbrexx3vqjhp41',
                content_type = 'image/png',
                filename = 'image.png',
                is_inline = True,
                size = 14039,
        )
        """

    def testAttachment(self):
        """Test Attachment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
