# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.message_participant_role import MessageParticipantRole

class TestMessageParticipantRole(unittest.TestCase):
    """MessageParticipantRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageParticipantRole(self):
        """Test MessageParticipantRole"""
        # inst = MessageParticipantRole()

if __name__ == '__main__':
    unittest.main()
