# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.api.drafts_api import DraftsApi


class TestDraftsApi(unittest.TestCase):
    """DraftsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DraftsApi()

    def tearDown(self) -> None:
        pass

    def test_create_draft(self) -> None:
        """Test case for create_draft

        Create a draft
        """
        pass

    def test_delete_draft(self) -> None:
        """Test case for delete_draft

        Delete a draft
        """
        pass

    def test_get_draft(self) -> None:
        """Test case for get_draft

        Retrieve a draft
        """
        pass

    def test_list_drafts(self) -> None:
        """Test case for list_drafts

        List drafts
        """
        pass

    def test_send_draft(self) -> None:
        """Test case for send_draft

        Send a draft
        """
        pass

    def test_update_draft(self) -> None:
        """Test case for update_draft

        Update a draft
        """
        pass


if __name__ == '__main__':
    unittest.main()
