# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.message import Message

class TestMessage(unittest.TestCase):
    """Message unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Message:
        """Test Message
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Message`
        """
        model = Message()
        if include_optional:
            return Message(
                id = 'msg_01hggtpfewf0y91nde7cz02p0k',
                channel_id = 'chnnl_01h2xcejqtf2nbrexx3vqjhp41',
                conversation_id = 'chnnl_01h2xcejqtf2nbrexx3vqjhp41',
                reply_to_message_id = 'msg_01h2xcejqtf2nbrexx3vqjhp41',
                reply_type = 'reply',
                subject = 'Issue with Verification Process',
                direction = 'inbound',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sender = convore_api_client.models.message_participant.MessageParticipant(
                    name = 'John Doe', 
                    handle = convore_api_client.models.contact_handle.ContactHandle(
                        type = 'email', 
                        value = 'john@example.com', ), 
                    role = 'from', ),
                recipients = [
                    convore_api_client.models.message_participant.MessageParticipant(
                        name = 'John Doe', 
                        handle = convore_api_client.models.contact_handle.ContactHandle(
                            type = 'email', 
                            value = 'john@example.com', ), 
                        role = 'from', )
                    ],
                snippet = '...',
                body = '...',
                text_body = '...',
                raw_body = '...',
                attachments = [
                    convore_api_client.models.attachment.Attachment(
                        id = 'attch_01hcf9x766fqk8g7hz74363j9q', 
                        conversation_id = 'conv_01h2xcejqtf2nbrexx3vqjhp41', 
                        draft_id = 'drft_01h2xcejqtf2nbrexx3vqjhp41', 
                        message_id = '', 
                        content_type = 'image/png', 
                        filename = 'image.png', 
                        is_inline = True, 
                        content_id = '', 
                        size = 14039, )
                    ],
                external_message_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                format = 'minimal'
            )
        else:
            return Message(
                id = 'msg_01hggtpfewf0y91nde7cz02p0k',
                channel_id = 'chnnl_01h2xcejqtf2nbrexx3vqjhp41',
                conversation_id = 'chnnl_01h2xcejqtf2nbrexx3vqjhp41',
                direction = 'inbound',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sender = convore_api_client.models.message_participant.MessageParticipant(
                    name = 'John Doe', 
                    handle = convore_api_client.models.contact_handle.ContactHandle(
                        type = 'email', 
                        value = 'john@example.com', ), 
                    role = 'from', ),
                recipients = [
                    convore_api_client.models.message_participant.MessageParticipant(
                        name = 'John Doe', 
                        handle = convore_api_client.models.contact_handle.ContactHandle(
                            type = 'email', 
                            value = 'john@example.com', ), 
                        role = 'from', )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                format = 'minimal',
        )
        """

    def testMessage(self):
        """Test Message"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
