# coding: utf-8

"""
    Convore API

    Convore API v1.0.0

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convore_api_client.models.event_type import EventType

class TestEventType(unittest.TestCase):
    """EventType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventType(self):
        """Test EventType"""
        # inst = EventType()

if __name__ == '__main__':
    unittest.main()
